module.exports = {
  'IGNORE': 'IGNORE',
  'DEBUG': 'DEBUG',
  'STATUSCODE': 'STATUSCODE',
  'TOTALTIME': 'TOTALTIME',
  'RESOURCEERROR': 'RESOURCEERROR',
  'PAGEERROR': 'PAGEERROR',
  'TOTALRESOURCES': 'TOTALRESOURCES',
  'RENDERTIME': 'RENDERTIME',
  'CONSOLEMSG': 'CONSOLEMSG',
  'SCREENSHOT': 'SCREENSHOT'
};
